name: pr_checker
on:
  pull_request_target:
    types:
    - opened
    - edited
    - synchronize
    - labeled
    - unlabeled
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: thehanimo/pr-title-checker@8464c95d2f82d7ab89496f544d48c799497c130b  # v1.3.6
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pass_on_octokit_error: false
        configuration_path: .github/pr-title-checker-config.json